import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return ( 
    <html lang="en" className=''>
      <body className= {['min-h-screen  bg-blue-800/25 ', inter.className ]}>        
        {children}        
        <footer> 
          <p className='text-center'>Made with ❤ by XavCode</p>
        </footer>
        </body>
    </html>
  )
}
